name: Deploy via FTP

on:
  push:
    branches:
      - main # Define o branch que dispara o deploy (alterar para o branch do seu projeto)

jobs:
  build-and-deploy:
    name: Build and Deploy to FTP
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.4 # Certifique-se de usar a versão correta para seu projeto Angular

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Construir o projeto Angular
      - name: Build Angular project
        run: npm run build

      # Fazer o upload via FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /dist/trilhar/browser # Diretório local gerado pelo Angular
          server-dir: /trilhar.IQUES.COM.BR # Diretório no servidor FTP
