name: Deploy via FTP

on:
  push:
    branches:
      - main
  #pull_request:
  #  branches:
  #    - main

  # Permite que você execute este fluxo de trabalho manualmente na guia Ações
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checando do GitHub Action
      uses: actions/checkout@v4

    - name: Configurando o NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18.20.4
    
    - name: Instalando pacotes com npm install
      run: npm install
    
    # Compilação com base-href
    - name: Construindo em produção
      run: npm run build -- --base-href /
    
    # Criando o arquivo web.config para IIS
    - name: Criando arquivo web.config
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <configuration>
          <system.webServer>
            <rewrite>
              <rules>
                <rule name="Angular Routes" stopProcessing="true">
                  <match url=".*" />
                  <conditions logicalGrouping="MatchAll">
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                  </conditions>
                  <action type="Rewrite" url="/" />
                </rule>
              </rules>
            </rewrite>
          </system.webServer>
        </configuration>' > dist/trilhar/browser/web.config
    
    # Mantendo o .htaccess como fallback
    - name: Criando arquivo .htaccess como fallback
      run: |
        echo '<IfModule mod_rewrite.c>
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
        </IfModule>' > dist/trilhar/browser/.htaccess
    
    - name: Subindo artefatos para serem usados no próximo fluxo
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: deploy_dist
        path: dist

  ftp-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Baixando artefatos criados no fluxo anterior
      if: success()
      uses: actions/download-artifact@v4
      with:
        name: deploy_dist
        path: dist
    
    # Verificação dos arquivos (debug)
    - name: Verificar estrutura de arquivos
      run: |
        ls -la dist/trilhar/browser/
        echo "Verificando arquivo web.config:"
        cat dist/trilhar/browser/web.config || echo "Arquivo web.config não encontrado"
        echo "Verificando arquivo .htaccess:"
        cat dist/trilhar/browser/.htaccess || echo "Arquivo .htaccess não encontrado"
    
    # Configuração do deploy FTP
    - name: Implantando no servidor FTP
      if: success()
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/trilhar/browser/
        server-dir: trilhar.iques.com.br/
        # protocol: ftps
        dangerous-clean-slate: true
        retries: 2
        retry-delay: 30
