name: Deploy via FTP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Permite que você execute este fluxo de trabalho manualmente na guia Ações
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checando do GitHub Action
      uses: actions/checkout@v3

    - name: Configurando o NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.20.4
    
    - name: Instalando pacotes com npm install
      run: npm install
    
    - name: Construíndo em produção com npm rum build
      run: npm run build
    
    - name: Subindo artefatos para serem usados no próximo fluxo
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: deploy_dist
        path: dist

  ftp-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Baixando artefatos criados no fluxo anterior
      if: success()
      uses: actions/download-artifact@v3
      with:
        name: deploy_dist
        path: dist
    
    - name: Implantando no servidor FTP
      if: success()
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/trilhar/browser/
        server-dir: trilhar.iques.com.br/
        protocol: ftps
        dangerous-clean-slate: true
        retries: 2   # Tentativas adicionais
        retry-delay: 30  # Atraso entre tentativas em segundos
